//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonicaExtra.Model.monicaextra
{
    using System;
    using System.Collections.Generic;
    
    public partial class cierrecaja
    {
        public short NumeroCierre { get; set; }
        public string FechaProceso { get; set; }
        public string FechaInicial { get; set; }
        public string FechaFinal { get; set; }
        public Nullable<short> NumeroCaja { get; set; }
        public Nullable<int> SaldoFinal { get; set; }
        public string Comentario { get; set; }
    }
}
