//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonicaExtra.Model.monicaextra
{
    using System;
    using System.Collections.Generic;
    
    public partial class clasificacionmovicaja
    {
        public short NumeroTransacion { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<short> FijarTipo { get; set; }
        public string Contable { get; set; }
        public Nullable<short> Visible { get; set; }
    }
}
