//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonicaExtra.Model.monicaextra
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class monicaextraEntities : DbContext
    {
        public monicaextraEntities()
            : base("name=monicaextraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cierrecaja> cierrecajas { get; set; }
        public virtual DbSet<clasificacionfiscal> clasificacionfiscals { get; set; }
        public virtual DbSet<clasificacionmovicaja> clasificacionmovicajas { get; set; }
        public virtual DbSet<movimientocaja> movimientocajas { get; set; }
    }
}
