//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonicaExtra.Model.monicaextra
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class usuario
    {
        public int id_usuario { get; set; }
        [Column("usuario")]
        public string usuario1 { get; set; }
        public string clave { get; set; }
        public string categoria { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nombre_completo { get; set; }
        public string animal { get; set; }
        public string plato { get; set; }
    }
}
