//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonicaExtra.Model.monica_global
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int empresa_id { get; set; }
        public string Nombre_empresa { get; set; }
        public string base_de_datos { get; set; }
        public int Condicion { get; set; }
        public string icono_asociado { get; set; }
        public string folder_empresa { get; set; }
        public string Registro_Tributario_empresa { get; set; }
        public string direccion1 { get; set; }
        public string direccion2 { get; set; }
        public string direccion3 { get; set; }
        public string Telefono1 { get; set; }
        public string celular { get; set; }
        public string Fax { get; set; }
        public string correo_electronico { get; set; }
        public string sitio_web { get; set; }
        public string registro_empresarial { get; set; }
        public string barrio_distrito { get; set; }
        public string ciudad { get; set; }
        public string codigo_postal { get; set; }
        public string pais { get; set; }
        public string logo { get; set; }
    }
}
